name: 02 - Workflow Events

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger 
              run: echo "I've been triggerd by a(n) ${{github.event_path}} event "